#include "font_small.h"

/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: D:/disk/projects/2022/FONTS/Font_ALL_letters_small_bold.xml
* name: LCD_All_Bolt
* family: Calibri
* size: 14
* style: Bold
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЪЬЭЮЯабвгдежзийклмнопрстуфхцчшщыъьэюя\x0011
* antialiasing: no
* type: proportional
* encoding: windows-1251
* unicode bom: no
*
* preset name: MonochromeVertical
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 100
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>



#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x11[5] = {
    
    0x00, 
    0x60, 
    0x90, 
    0x90, 
    0x60
};
static const tImage Font_0x11 = { image_data_Font_0x11,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x20[2] = {
    
    0x00, 
    0x00
};
static const tImage Font_0x20 = { image_data_Font_0x20,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x21[2] = {
    
    0x00, 
    0xfa
};
static const tImage Font_0x21 = { image_data_Font_0x21,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x22[4] = {
    
    0x00, 
    0xe0, 
    0x00, 
    0xe0
};
static const tImage Font_0x22 = { image_data_Font_0x22,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x23[6] = {
    
    0x00, 
    0x28, 
    0x7c, 
    0x28, 
    0x7c, 
    0x28
};
static const tImage Font_0x23 = { image_data_Font_0x23,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x24[5] = {
    
    0x00, 
    0x72, 
    0x53, 
    0xca, 
    0x4e
};
static const tImage Font_0x24 = { image_data_Font_0x24,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x25[8] = {
    
    0x00, 
    0xf0, 
    0x92, 
    0xfc, 
    0x10, 
    0x7e, 
    0x92, 
    0x1e
};
static const tImage Font_0x25 = { image_data_Font_0x25,
    8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x26[7] = {
    
    0x00, 
    0x0c, 
    0xf2, 
    0x92, 
    0xea, 
    0x1c, 
    0x02
};
static const tImage Font_0x26 = { image_data_Font_0x26,
    7, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x27[2] = {
    
    0x00, 
    0xe0
};
static const tImage Font_0x27 = { image_data_Font_0x27,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x28[3] = {
    
    0x00, 
    0x7e, 
    0x81
};
static const tImage Font_0x28 = { image_data_Font_0x28,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x29[3] = {
    
    0x00, 
    0x81, 
    0x7e
};
static const tImage Font_0x29 = { image_data_Font_0x29,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2a[5] = {
    
    0x00, 
    0x40, 
    0xe0, 
    0x40, 
    0x00
};
static const tImage Font_0x2a = { image_data_Font_0x2a,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2b[6] = {
    
    0x00, 
    0x10, 
    0x10, 
    0x7c, 
    0x10, 
    0x10
};
static const tImage Font_0x2b = { image_data_Font_0x2b,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2c[2] = {
    
    0x01, 
    0x02
};
static const tImage Font_0x2c = { image_data_Font_0x2c,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2d[6] = {
    
    0x00, 
    0x10, 
    0x10, 
    0x10, 
    0x10, 
    0x10
};
static const tImage Font_0x2d = { image_data_Font_0x2d,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2e[2] = {
    
    0x00, 
    0x02
};
static const tImage Font_0x2e = { image_data_Font_0x2e,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2f[5] = {
    
    0x00, 
    0x01, 
    0x0e, 
    0x70, 
    0x80
};
static const tImage Font_0x2f = { image_data_Font_0x2f,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x30[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x3c
};
static const tImage Font_0x30 = { image_data_Font_0x30,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x31[5] = {
    
    0x00, 
    0x22, 
    0x22, 
    0x7e, 
    0x02
};
static const tImage Font_0x31 = { image_data_Font_0x31,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x32[5] = {
    
    0x00, 
    0x22, 
    0x46, 
    0x4a, 
    0x32
};
static const tImage Font_0x32 = { image_data_Font_0x32,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x33[5] = {
    
    0x00, 
    0x42, 
    0x52, 
    0x52, 
    0x2c
};
static const tImage Font_0x33 = { image_data_Font_0x33,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x34[5] = {
    
    0x00, 
    0x1c, 
    0x24, 
    0x7e, 
    0x04
};
static const tImage Font_0x34 = { image_data_Font_0x34,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x35[5] = {
    
    0x00, 
    0x72, 
    0x52, 
    0x52, 
    0x4c
};
static const tImage Font_0x35 = { image_data_Font_0x35,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x36[5] = {
    
    0x00, 
    0x3c, 
    0x52, 
    0x52, 
    0x0c
};
static const tImage Font_0x36 = { image_data_Font_0x36,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x37[5] = {
    
    0x00, 
    0x40, 
    0x4e, 
    0x50, 
    0x60
};
static const tImage Font_0x37 = { image_data_Font_0x37,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x38[5] = {
    
    0x00, 
    0x2c, 
    0x52, 
    0x52, 
    0x2c
};
static const tImage Font_0x38 = { image_data_Font_0x38,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x39[5] = {
    
    0x00, 
    0x30, 
    0x4a, 
    0x4a, 
    0x3c
};
static const tImage Font_0x39 = { image_data_Font_0x39,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3a[2] = {
    
    0x00, 
    0x12
};
static const tImage Font_0x3a = { image_data_Font_0x3a,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3b[3] = {
    
    0x00, 
    0x01, 
    0x12
};
static const tImage Font_0x3b = { image_data_Font_0x3b,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3c[5] = {
    
    0x00, 
    0x10, 
    0x28, 
    0x28, 
    0x44
};
static const tImage Font_0x3c = { image_data_Font_0x3c,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3d[5] = {
    
    0x00, 
    0x14, 
    0x14, 
    0x14, 
    0x14
};
static const tImage Font_0x3d = { image_data_Font_0x3d,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3e[5] = {
    
    0x00, 
    0x44, 
    0x28, 
    0x28, 
    0x10
};
static const tImage Font_0x3e = { image_data_Font_0x3e,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3f[4] = {
    
    0x00, 
    0x80, 
    0x9a, 
    0xf0
};
static const tImage Font_0x3f = { image_data_Font_0x3f,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x40[8] = {
    
    0x00, 
    0x1e, 
    0x23, 
    0x5d, 
    0x55, 
    0x5d, 
    0x44, 
    0x38
};
static const tImage Font_0x40 = { image_data_Font_0x40,
    8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x41[6] = {
    
    0x00, 
    0x06, 
    0x18, 
    0x68, 
    0x18, 
    0x06
};
static const tImage Font_0x41 = { image_data_Font_0x41,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x42[4] = {
    
    0x00, 
    0x7e, 
    0x52, 
    0x2c
};
static const tImage Font_0x42 = { image_data_Font_0x42,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x43[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x24
};
static const tImage Font_0x43 = { image_data_Font_0x43,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x44[4] = {
    
    0x00, 
    0x7e, 
    0x42, 
    0x3c
};
static const tImage Font_0x44 = { image_data_Font_0x44,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x45[4] = {
    
    0x00, 
    0x7e, 
    0x52, 
    0x52
};
static const tImage Font_0x45 = { image_data_Font_0x45,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x46[4] = {
    
    0x00, 
    0x7e, 
    0x50, 
    0x50
};
static const tImage Font_0x46 = { image_data_Font_0x46,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x47[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x4a, 
    0x2e
};
static const tImage Font_0x47 = { image_data_Font_0x47,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x48[4] = {
    
    0x00, 
    0x7e, 
    0x10, 
    0x7e
};
static const tImage Font_0x48 = { image_data_Font_0x48,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x49[4] = {
    
    0x00, 
    0x42, 
    0x7e, 
    0x42
};
static const tImage Font_0x49 = { image_data_Font_0x49,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4a[4] = {
    
    0x00, 
    0x06, 
    0x02, 
    0x7e
};
static const tImage Font_0x4a = { image_data_Font_0x4a,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4b[5] = {
    
    0x00, 
    0x7e, 
    0x18, 
    0x24, 
    0x42
};
static const tImage Font_0x4b = { image_data_Font_0x4b,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4c[4] = {
    
    0x00, 
    0x7e, 
    0x02, 
    0x02
};
static const tImage Font_0x4c = { image_data_Font_0x4c,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4d[6] = {
    
    0x00, 
    0x7e, 
    0x20, 
    0x1c, 
    0x20, 
    0x7e
};
static const tImage Font_0x4d = { image_data_Font_0x4d,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4e[5] = {
    
    0x00, 
    0x7e, 
    0x30, 
    0x0c, 
    0x7e
};
static const tImage Font_0x4e = { image_data_Font_0x4e,
    5, 8, 8};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_Font_0x4f[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x3c
};
static const tImage Font_0x4f = { image_data_Font_0x4f,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x50[4] = {
    
    0x00, 
    0x7e, 
    0x48, 
    0x30
};
static const tImage Font_0x50 = { image_data_Font_0x50,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x51[6] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x3e, 
    0x01
};
static const tImage Font_0x51 = { image_data_Font_0x51,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x52[5] = {
    
    0x00, 
    0x7e, 
    0x48, 
    0x4c, 
    0x32
};
static const tImage Font_0x52 = { image_data_Font_0x52,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x53[5] = {
    
    0x00, 
    0x32, 
    0x52, 
    0x4a, 
    0x4c
};
static const tImage Font_0x53 = { image_data_Font_0x53,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x54[4] = {
    
    0x00, 
    0x40, 
    0x7e, 
    0x40
};
static const tImage Font_0x54 = { image_data_Font_0x54,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x55[5] = {
    
    0x00, 
    0x7c, 
    0x02, 
    0x02, 
    0x7c
};
static const tImage Font_0x55 = { image_data_Font_0x55,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x56[6] = {
    
    0x00, 
    0x70, 
    0x0c, 
    0x02, 
    0x0c, 
    0x70
};
static const tImage Font_0x56 = { image_data_Font_0x56,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x57[6] = {
    
    0x00, 
    0x70, 
    0x0e, 
    0x78, 
    0x0e, 
    0x70
};
static const tImage Font_0x57 = { image_data_Font_0x57,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x58[4] = {
    
    0x00, 
    0x66, 
    0x18, 
    0x66
};
static const tImage Font_0x58 = { image_data_Font_0x58,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x59[6] = {
    
    0x00, 
    0x40, 
    0x30, 
    0x0e, 
    0x30, 
    0x40
};
static const tImage Font_0x59 = { image_data_Font_0x59,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5a[5] = {
    
    0x00, 
    0x46, 
    0x4a, 
    0x52, 
    0x62
};
static const tImage Font_0x5a = { image_data_Font_0x5a,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5b[3] = {
    
    0x00, 
    0xff, 
    0x81
};
static const tImage Font_0x5b = { image_data_Font_0x5b,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5c[4] = {
    
    0x80, 
    0x70, 
    0x0e, 
    0x01
};
static const tImage Font_0x5c = { image_data_Font_0x5c,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5d[3] = {
    
    0x00, 
    0x81, 
    0xff
};
static const tImage Font_0x5d = { image_data_Font_0x5d,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5e[5] = {
    
    0x14, 
    0x36, 
    0x77, 
    0x36, 
    0x14
};
static const tImage Font_0x5e = { image_data_Font_0x5e,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5f[5] = {
    
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x01
};
static const tImage Font_0x5f = { image_data_Font_0x5f,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x60[3] = {
    
    0x00, 
    0x80, 
    0x40
};
static const tImage Font_0x60 = { image_data_Font_0x60,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x61[4] = {
    
    0x00, 
    0x24, 
    0x2a, 
    0x1e
};
static const tImage Font_0x61 = { image_data_Font_0x61,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x62[4] = {
    
    0x00, 
    0xfe, 
    0x22, 
    0x1c
};
static const tImage Font_0x62 = { image_data_Font_0x62,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x63[4] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0x22
};
static const tImage Font_0x63 = { image_data_Font_0x63,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x64[4] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0xfe
};
static const tImage Font_0x64 = { image_data_Font_0x64,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x65[5] = {
    
    0x00, 
    0x1c, 
    0x2a, 
    0x2a, 
    0x1a
};
static const tImage Font_0x65 = { image_data_Font_0x65,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x66[4] = {
    
    0x00, 
    0x20, 
    0x7e, 
    0xa0
};
static const tImage Font_0x66 = { image_data_Font_0x66,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x67[4] = {
    
    0x00, 
    0x26, 
    0x52, 
    0x7e
};
static const tImage Font_0x67 = { image_data_Font_0x67,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x68[4] = {
    
    0x00, 
    0xfe, 
    0x20, 
    0x1e
};
static const tImage Font_0x68 = { image_data_Font_0x68,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x69[2] = {
    
    0x00, 
    0xbe
};
static const tImage Font_0x69 = { image_data_Font_0x69,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6a[3] = {
    
    0x00, 
    0x01, 
    0xbe
};
static const tImage Font_0x6a = { image_data_Font_0x6a,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6b[4] = {
    
    0x00, 
    0xfe, 
    0x08, 
    0x36
};
static const tImage Font_0x6b = { image_data_Font_0x6b,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6c[2] = {
    
    0x00, 
    0xfe
};
static const tImage Font_0x6c = { image_data_Font_0x6c,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6d[6] = {
    
    0x00, 
    0x3e, 
    0x20, 
    0x1c, 
    0x20, 
    0x1e
};
static const tImage Font_0x6d = { image_data_Font_0x6d,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6e[4] = {
    
    0x00, 
    0x3e, 
    0x20, 
    0x1e
};
static const tImage Font_0x6e = { image_data_Font_0x6e,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6f[4] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0x1c
};
static const tImage Font_0x6f = { image_data_Font_0x6f,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x70[4] = {
    
    0x00, 
    0x3f, 
    0x24, 
    0x18
};
static const tImage Font_0x70 = { image_data_Font_0x70,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x71[4] = {
    
    0x00, 
    0x18, 
    0x24, 
    0x3f
};
static const tImage Font_0x71 = { image_data_Font_0x71,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x72[3] = {
    
    0x00, 
    0x3e, 
    0x20
};
static const tImage Font_0x72 = { image_data_Font_0x72,
    3, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x73[4] = {
    
    0x00, 
    0x12, 
    0x2a, 
    0x24
};
static const tImage Font_0x73 = { image_data_Font_0x73,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x74[4] = {
    
    0x00, 
    0x20, 
    0x7c, 
    0x22
};
static const tImage Font_0x74 = { image_data_Font_0x74,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x75[5] = {
    
    0x00, 
    0x3c, 
    0x02, 
    0x02, 
    0x3e
};
static const tImage Font_0x75 = { image_data_Font_0x75,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x76[4] = {
    
    0x00, 
    0x38, 
    0x06, 
    0x38
};
static const tImage Font_0x76 = { image_data_Font_0x76,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x77[6] = {
    
    0x00, 
    0x38, 
    0x06, 
    0x18, 
    0x06, 
    0x38
};
static const tImage Font_0x77 = { image_data_Font_0x77,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x78[4] = {
    
    0x00, 
    0x36, 
    0x08, 
    0x36
};
static const tImage Font_0x78 = { image_data_Font_0x78,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x79[4] = {
    
    0x00, 
    0x39, 
    0x06, 
    0x38
};
static const tImage Font_0x79 = { image_data_Font_0x79,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7a[4] = {
    
    0x00, 
    0x26, 
    0x2a, 
    0x32
};
static const tImage Font_0x7a = { image_data_Font_0x7a,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7b[4] = {
    
    0x00, 
    0x08, 
    0xf7, 
    0x81
};
static const tImage Font_0x7b = { image_data_Font_0x7b,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7c[2] = {
    
    0x00, 
    0xff
};
static const tImage Font_0x7c = { image_data_Font_0x7c,
    2, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7d[4] = {
    
    0x00, 
    0x81, 
    0xf7, 
    0x08
};
static const tImage Font_0x7d = { image_data_Font_0x7d,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7e[5] = {
    
    0x00, 
    0x60, 
    0x40, 
    0x20, 
    0x60
};
static const tImage Font_0x7e = { image_data_Font_0x7e,
    5, 8, 8};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_Font_0xc0[6] = {
    
    0x00, 
    0x06, 
    0x18, 
    0x68, 
    0x18, 
    0x06
};
static const tImage Font_0xc0 = { image_data_Font_0xc0,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc1[5] = {
    
    0x00, 
    0x7e, 
    0x52, 
    0x52, 
    0x5c
};
static const tImage Font_0xc1 = { image_data_Font_0xc1,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc2[5] = {
    
    0x00, 
    0x7e, 
    0x52, 
    0x52, 
    0x6c
};
static const tImage Font_0xc2 = { image_data_Font_0xc2,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc3[4] = {
    
    0x00, 
    0x7e, 
    0x40, 
    0x40
};
static const tImage Font_0xc3 = { image_data_Font_0xc3,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc4[7] = {
    
    0x00, 
    0x03, 
    0x0e, 
    0x72, 
    0x42, 
    0x7e, 
    0x03
};
static const tImage Font_0xc4 = { image_data_Font_0xc4,
    7, 8, 8};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_Font_0xc5[4] = {
    
    0x00, 
    0x7e, 
    0x52, 
    0x52
};
static const tImage Font_0xc5 = { image_data_Font_0xc5,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc6[6] = {
    
    0x00, 
    0x6e, 
    0x10, 
    0x7e, 
    0x10, 
    0x6e
};
static const tImage Font_0xc6 = { image_data_Font_0xc6,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc7[5] = {
    
    0x00, 
    0x42, 
    0x52, 
    0x52, 
    0x6c
};
static const tImage Font_0xc7 = { image_data_Font_0xc7,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xc8[6] = {
    
    0x00, 
    0x00, 
    0x7e, 
    0x0c, 
    0x30, 
    0x7e
};
static const tImage Font_0xc8 = { image_data_Font_0xc8,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xca[5] = {
    
    0x00, 
    0x7e, 
    0x10, 
    0x2c, 
    0x42
};
static const tImage Font_0xca = { image_data_Font_0xca,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xcb[5] = {
    
    0x00, 
    0x02, 
    0x7c, 
    0x40, 
    0x7e
};
static const tImage Font_0xcb = { image_data_Font_0xcb,
    5, 8, 8};
#endif

#if (0x04d == 0x0)
static const uint8_t image_data_Font_0xcc[6] = {
    
    0x00, 
    0x7e, 
    0x20, 
    0x1c, 
    0x20, 
    0x7e
};
static const tImage Font_0xcc = { image_data_Font_0xcc,
    6, 8, 8};
#endif

#if (0x048 == 0x0)
static const uint8_t image_data_Font_0xcd[4] = {
    
    0x00, 
    0x7e, 
    0x10, 
    0x7e
};
static const tImage Font_0xcd = { image_data_Font_0xcd,
    4, 8, 8};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_Font_0xce[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x3c
};
static const tImage Font_0xce = { image_data_Font_0xce,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xcf[4] = {
    
    0x00, 
    0x7e, 
    0x40, 
    0x7e
};
static const tImage Font_0xcf = { image_data_Font_0xcf,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd0[4] = {
    
    0x00, 
    0x7e, 
    0x48, 
    0x78
};
static const tImage Font_0xd0 = { image_data_Font_0xd0,
    4, 8, 8};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_Font_0xd1[5] = {
    
    0x00, 
    0x3c, 
    0x42, 
    0x42, 
    0x24
};
static const tImage Font_0xd1 = { image_data_Font_0xd1,
    5, 8, 8};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_Font_0xd2[4] = {
    
    0x00, 
    0x40, 
    0x7e, 
    0x40
};
static const tImage Font_0xd2 = { image_data_Font_0xd2,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd3[6] = {
    
    0x00, 
    0x42, 
    0x7a, 
    0x04, 
    0x78, 
    0x40
};
static const tImage Font_0xd3 = { image_data_Font_0xd3,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd4[6] = {
    
    0x00, 
    0x3c, 
    0x24, 
    0x7e, 
    0x24, 
    0x3c
};
static const tImage Font_0xd4 = { image_data_Font_0xd4,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd5[6] = {
    
    0x00, 
    0x42, 
    0x24, 
    0x18, 
    0x24, 
    0x42
};
static const tImage Font_0xd5 = { image_data_Font_0xd5,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd6[5] = {
    
    0x00, 
    0x7e, 
    0x02, 
    0x7e, 
    0x03
};
static const tImage Font_0xd6 = { image_data_Font_0xd6,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd7[5] = {
    
    0x00, 
    0x70, 
    0x08, 
    0x08, 
    0x7e
};
static const tImage Font_0xd7 = { image_data_Font_0xd7,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd8[6] = {
    
    0x00, 
    0x7e, 
    0x02, 
    0x7e, 
    0x02, 
    0x7e
};
static const tImage Font_0xd8 = { image_data_Font_0xd8,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xd9[7] = {
    
    0x00, 
    0x7e, 
    0x02, 
    0x7e, 
    0x02, 
    0x7e, 
    0x03
};
static const tImage Font_0xd9 = { image_data_Font_0xd9,
    7, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xda[6] = {
    
    0x00, 
    0x40, 
    0x7e, 
    0x12, 
    0x12, 
    0x0c
};
static const tImage Font_0xda = { image_data_Font_0xda,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xdc[5] = {
    
    0x00, 
    0x7e, 
    0x12, 
    0x12, 
    0x0c
};
static const tImage Font_0xdc = { image_data_Font_0xdc,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xdd[6] = {
    
    0x00, 
    0x42, 
    0x52, 
    0x52, 
    0x76, 
    0x3c
};
static const tImage Font_0xdd = { image_data_Font_0xdd,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xde[7] = {
    
    0x00, 
    0x7e, 
    0x10, 
    0x3c, 
    0x42, 
    0x42, 
    0x3c
};
static const tImage Font_0xde = { image_data_Font_0xde,
    7, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xdf[5] = {
    
    0x00, 
    0x32, 
    0x4c, 
    0x48, 
    0x7e
};
static const tImage Font_0xdf = { image_data_Font_0xdf,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe0[5] = {
    
    0x00, 
    0x04, 
    0x2a, 
    0x2a, 
    0x1e
};
static const tImage Font_0xe0 = { image_data_Font_0xe0,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe1[4] = {
    
    0x00, 
    0x7c, 
    0xa2, 
    0x9c
};
static const tImage Font_0xe1 = { image_data_Font_0xe1,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe2[4] = {
    
    0x00, 
    0x3e, 
    0x2a, 
    0x14
};
static const tImage Font_0xe2 = { image_data_Font_0xe2,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe3[4] = {
    
    0x00, 
    0x3e, 
    0x20, 
    0x20
};
static const tImage Font_0xe3 = { image_data_Font_0xe3,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe4[6] = {
    
    0x00, 
    0x07, 
    0x3a, 
    0x22, 
    0x3e, 
    0x03
};
static const tImage Font_0xe4 = { image_data_Font_0xe4,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe5[5] = {
    
    0x00, 
    0x1c, 
    0x2a, 
    0x2a, 
    0x18
};
static const tImage Font_0xe5 = { image_data_Font_0xe5,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe6[6] = {
    
    0x00, 
    0x36, 
    0x08, 
    0x3e, 
    0x08, 
    0x36
};
static const tImage Font_0xe6 = { image_data_Font_0xe6,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe7[4] = {
    
    0x00, 
    0x22, 
    0x2a, 
    0x36
};
static const tImage Font_0xe7 = { image_data_Font_0xe7,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe8[5] = {
    
    0x00, 
    0x3e, 
    0x0c, 
    0x10, 
    0x3e
};
static const tImage Font_0xe8 = { image_data_Font_0xe8,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xe9[5] = {
    
    0x00, 
    0x3e, 
    0x8c, 
    0x90, 
    0x3e
};
static const tImage Font_0xe9 = { image_data_Font_0xe9,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xea[4] = {
    
    0x00, 
    0x3e, 
    0x08, 
    0x36
};
static const tImage Font_0xea = { image_data_Font_0xea,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xeb[5] = {
    
    0x00, 
    0x02, 
    0x3c, 
    0x20, 
    0x3e
};
static const tImage Font_0xeb = { image_data_Font_0xeb,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xec[6] = {
    
    0x00, 
    0x3e, 
    0x20, 
    0x1c, 
    0x20, 
    0x3e
};
static const tImage Font_0xec = { image_data_Font_0xec,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xed[4] = {
    
    0x00, 
    0x3e, 
    0x08, 
    0x3e
};
static const tImage Font_0xed = { image_data_Font_0xed,
    4, 8, 8};
#endif

#if (0x06f == 0x0)
static const uint8_t image_data_Font_0xee[4] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0x1c
};
static const tImage Font_0xee = { image_data_Font_0xee,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xef[4] = {
    
    0x00, 
    0x3e, 
    0x20, 
    0x3e
};
static const tImage Font_0xef = { image_data_Font_0xef,
    4, 8, 8};
#endif

#if (0x070 == 0x0)
static const uint8_t image_data_Font_0xf0[4] = {
    
    0x00, 
    0x3f, 
    0x24, 
    0x18
};
static const tImage Font_0xf0 = { image_data_Font_0xf0,
    4, 8, 8};
#endif

#if (0x063 == 0x0)
static const uint8_t image_data_Font_0xf1[4] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0x22
};
static const tImage Font_0xf1 = { image_data_Font_0xf1,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf2[4] = {
    
    0x00, 
    0x20, 
    0x3e, 
    0x20
};
static const tImage Font_0xf2 = { image_data_Font_0xf2,
    4, 8, 8};
#endif

#if (0x079 == 0x0)
static const uint8_t image_data_Font_0xf3[4] = {
    
    0x00, 
    0x39, 
    0x06, 
    0x38
};
static const tImage Font_0xf3 = { image_data_Font_0xf3,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf4[6] = {
    
    0x00, 
    0x1c, 
    0x22, 
    0x7f, 
    0x22, 
    0x1c
};
static const tImage Font_0xf4 = { image_data_Font_0xf4,
    6, 8, 8};
#endif

#if (0x078 == 0x0)
static const uint8_t image_data_Font_0xf5[4] = {
    
    0x00, 
    0x36, 
    0x08, 
    0x36
};
static const tImage Font_0xf5 = { image_data_Font_0xf5,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf6[5] = {
    
    0x00, 
    0x3e, 
    0x02, 
    0x3e, 
    0x03
};
static const tImage Font_0xf6 = { image_data_Font_0xf6,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf7[4] = {
    
    0x00, 
    0x38, 
    0x08, 
    0x3e
};
static const tImage Font_0xf7 = { image_data_Font_0xf7,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf8[6] = {
    
    0x00, 
    0x3e, 
    0x02, 
    0x3e, 
    0x02, 
    0x3e
};
static const tImage Font_0xf8 = { image_data_Font_0xf8,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xf9[7] = {
    
    0x00, 
    0x3e, 
    0x02, 
    0x3e, 
    0x02, 
    0x3e, 
    0x03
};
static const tImage Font_0xf9 = { image_data_Font_0xf9,
    7, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xfa[5] = {
    
    0x00, 
    0x20, 
    0x3e, 
    0x0a, 
    0x0c
};
static const tImage Font_0xfa = { image_data_Font_0xfa,
    5, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xfb[6] = {
    
    0x00, 
    0x3e, 
    0x0a, 
    0x0c, 
    0x00, 
    0x3e
};
static const tImage Font_0xfb = { image_data_Font_0xfb,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xfc[4] = {
    
    0x00, 
    0x3e, 
    0x0a, 
    0x0c
};
static const tImage Font_0xfc = { image_data_Font_0xfc,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xfd[4] = {
    
    0x00, 
    0x2a, 
    0x2a, 
    0x1c
};
static const tImage Font_0xfd = { image_data_Font_0xfd,
    4, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xfe[6] = {
    
    0x00, 
    0x3e, 
    0x08, 
    0x1c, 
    0x22, 
    0x1c
};
static const tImage Font_0xfe = { image_data_Font_0xfe,
    6, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0xff[4] = {
    
    0x00, 
    0x16, 
    0x28, 
    0x3e
};
static const tImage Font_0xff = { image_data_Font_0xff,
    4, 8, 8};
#endif


static const tChar Font_array[] = {

#if (0x0 == 0x0)
  // character: '\x0011'
  {0x11, &Font_0x11},
#else
  // character: '\x0011' == ''
  {0x11, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_0x},
#endif

#if (0x030 == 0x0)
  // character: 'O'
  {0x4f, &Font_0x4f},
#else
  // character: 'O' == '0'
  {0x4f, &Font_0x30},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &Font_0x6c},
#else
  // character: 'l' == ''
  {0x6c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_0x7e},
#else
  // character: '~' == ''
  {0x7e, &Font_0x},
#endif

#if (0x041 == 0x0)
  // character: 'А'
  {0xc0, &Font_0xc0},
#else
  // character: 'А' == 'A'
  {0xc0, &Font_0x41},
#endif

#if (0x0 == 0x0)
  // character: 'Б'
  {0xc1, &Font_0xc1},
#else
  // character: 'Б' == ''
  {0xc1, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'В'
  {0xc2, &Font_0xc2},
#else
  // character: 'В' == ''
  {0xc2, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Г'
  {0xc3, &Font_0xc3},
#else
  // character: 'Г' == ''
  {0xc3, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Д'
  {0xc4, &Font_0xc4},
#else
  // character: 'Д' == ''
  {0xc4, &Font_0x},
#endif

#if (0x045 == 0x0)
  // character: 'Е'
  {0xc5, &Font_0xc5},
#else
  // character: 'Е' == 'E'
  {0xc5, &Font_0x45},
#endif

#if (0x0 == 0x0)
  // character: 'Ж'
  {0xc6, &Font_0xc6},
#else
  // character: 'Ж' == ''
  {0xc6, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'З'
  {0xc7, &Font_0xc7},
#else
  // character: 'З' == ''
  {0xc7, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'И'
  {0xc8, &Font_0xc8},
#else
  // character: 'И' == ''
  {0xc8, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'К'
  {0xca, &Font_0xca},
#else
  // character: 'К' == ''
  {0xca, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Л'
  {0xcb, &Font_0xcb},
#else
  // character: 'Л' == ''
  {0xcb, &Font_0x},
#endif

#if (0x04d == 0x0)
  // character: 'М'
  {0xcc, &Font_0xcc},
#else
  // character: 'М' == 'M'
  {0xcc, &Font_0x4d},
#endif

#if (0x048 == 0x0)
  // character: 'Н'
  {0xcd, &Font_0xcd},
#else
  // character: 'Н' == 'H'
  {0xcd, &Font_0x48},
#endif

#if (0x030 == 0x0)
  // character: 'О'
  {0xce, &Font_0xce},
#else
  // character: 'О' == '0'
  {0xce, &Font_0x30},
#endif

#if (0x0 == 0x0)
  // character: 'П'
  {0xcf, &Font_0xcf},
#else
  // character: 'П' == ''
  {0xcf, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Р'
  {0xd0, &Font_0xd0},
#else
  // character: 'Р' == ''
  {0xd0, &Font_0x},
#endif

#if (0x043 == 0x0)
  // character: 'С'
  {0xd1, &Font_0xd1},
#else
  // character: 'С' == 'C'
  {0xd1, &Font_0x43},
#endif

#if (0x054 == 0x0)
  // character: 'Т'
  {0xd2, &Font_0xd2},
#else
  // character: 'Т' == 'T'
  {0xd2, &Font_0x54},
#endif

#if (0x0 == 0x0)
  // character: 'У'
  {0xd3, &Font_0xd3},
#else
  // character: 'У' == ''
  {0xd3, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ф'
  {0xd4, &Font_0xd4},
#else
  // character: 'Ф' == ''
  {0xd4, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Х'
  {0xd5, &Font_0xd5},
#else
  // character: 'Х' == ''
  {0xd5, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ц'
  {0xd6, &Font_0xd6},
#else
  // character: 'Ц' == ''
  {0xd6, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ч'
  {0xd7, &Font_0xd7},
#else
  // character: 'Ч' == ''
  {0xd7, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ш'
  {0xd8, &Font_0xd8},
#else
  // character: 'Ш' == ''
  {0xd8, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Щ'
  {0xd9, &Font_0xd9},
#else
  // character: 'Щ' == ''
  {0xd9, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ъ'
  {0xda, &Font_0xda},
#else
  // character: 'Ъ' == ''
  {0xda, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ь'
  {0xdc, &Font_0xdc},
#else
  // character: 'Ь' == ''
  {0xdc, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Э'
  {0xdd, &Font_0xdd},
#else
  // character: 'Э' == ''
  {0xdd, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ю'
  {0xde, &Font_0xde},
#else
  // character: 'Ю' == ''
  {0xde, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Я'
  {0xdf, &Font_0xdf},
#else
  // character: 'Я' == ''
  {0xdf, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'а'
  {0xe0, &Font_0xe0},
#else
  // character: 'а' == ''
  {0xe0, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'б'
  {0xe1, &Font_0xe1},
#else
  // character: 'б' == ''
  {0xe1, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'в'
  {0xe2, &Font_0xe2},
#else
  // character: 'в' == ''
  {0xe2, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'г'
  {0xe3, &Font_0xe3},
#else
  // character: 'г' == ''
  {0xe3, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'д'
  {0xe4, &Font_0xe4},
#else
  // character: 'д' == ''
  {0xe4, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'е'
  {0xe5, &Font_0xe5},
#else
  // character: 'е' == ''
  {0xe5, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ж'
  {0xe6, &Font_0xe6},
#else
  // character: 'ж' == ''
  {0xe6, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'з'
  {0xe7, &Font_0xe7},
#else
  // character: 'з' == ''
  {0xe7, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'и'
  {0xe8, &Font_0xe8},
#else
  // character: 'и' == ''
  {0xe8, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'й'
  {0xe9, &Font_0xe9},
#else
  // character: 'й' == ''
  {0xe9, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'к'
  {0xea, &Font_0xea},
#else
  // character: 'к' == ''
  {0xea, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'л'
  {0xeb, &Font_0xeb},
#else
  // character: 'л' == ''
  {0xeb, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'м'
  {0xec, &Font_0xec},
#else
  // character: 'м' == ''
  {0xec, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'н'
  {0xed, &Font_0xed},
#else
  // character: 'н' == ''
  {0xed, &Font_0x},
#endif

#if (0x06f == 0x0)
  // character: 'о'
  {0xee, &Font_0xee},
#else
  // character: 'о' == 'o'
  {0xee, &Font_0x6f},
#endif

#if (0x0 == 0x0)
  // character: 'п'
  {0xef, &Font_0xef},
#else
  // character: 'п' == ''
  {0xef, &Font_0x},
#endif

#if (0x070 == 0x0)
  // character: 'р'
  {0xf0, &Font_0xf0},
#else
  // character: 'р' == 'p'
  {0xf0, &Font_0x70},
#endif

#if (0x063 == 0x0)
  // character: 'с'
  {0xf1, &Font_0xf1},
#else
  // character: 'с' == 'c'
  {0xf1, &Font_0x63},
#endif

#if (0x0 == 0x0)
  // character: 'т'
  {0xf2, &Font_0xf2},
#else
  // character: 'т' == ''
  {0xf2, &Font_0x},
#endif

#if (0x079 == 0x0)
  // character: 'у'
  {0xf3, &Font_0xf3},
#else
  // character: 'у' == 'y'
  {0xf3, &Font_0x79},
#endif

#if (0x0 == 0x0)
  // character: 'ф'
  {0xf4, &Font_0xf4},
#else
  // character: 'ф' == ''
  {0xf4, &Font_0x},
#endif

#if (0x078 == 0x0)
  // character: 'х'
  {0xf5, &Font_0xf5},
#else
  // character: 'х' == 'x'
  {0xf5, &Font_0x78},
#endif

#if (0x0 == 0x0)
  // character: 'ц'
  {0xf6, &Font_0xf6},
#else
  // character: 'ц' == ''
  {0xf6, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ч'
  {0xf7, &Font_0xf7},
#else
  // character: 'ч' == ''
  {0xf7, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ш'
  {0xf8, &Font_0xf8},
#else
  // character: 'ш' == ''
  {0xf8, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'щ'
  {0xf9, &Font_0xf9},
#else
  // character: 'щ' == ''
  {0xf9, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ъ'
  {0xfa, &Font_0xfa},
#else
  // character: 'ъ' == ''
  {0xfa, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ы'
  {0xfb, &Font_0xfb},
#else
  // character: 'ы' == ''
  {0xfb, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ь'
  {0xfc, &Font_0xfc},
#else
  // character: 'ь' == ''
  {0xfc, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'э'
  {0xfd, &Font_0xfd},
#else
  // character: 'э' == ''
  {0xfd, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ю'
  {0xfe, &Font_0xfe},
#else
  // character: 'ю' == ''
  {0xfe, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'я'
  {0xff, &Font_0xff}
#else
  // character: 'я' == ''
  {0xff, &Font_0x}
#endif

};


const tFont ABB_Font[2] = { 158, Font_array };